# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12rhTW5i7kfHLn7a1qk5Y6_7VQRsUSD5D
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np


plt.rcParams['font.family'] = 'Malgun Gothic'
plt.rcParams['axes.unicode_minus'] = False


df = pd.read_excel('./노인운전자 연령층별 교통사고1.xls', skiprows=1)

df

#%%

# 칼럼명 수정

df.rename(columns={'사고[건]': '2019_사고[건]', '사망[명]' : '2019_사망[건]', '부상[명]' : '2019_부상[명]'}, inplace=True)
df.rename(columns={'사고[건].1': '2020_사고[건]', '사망[명].1' : '2020_사망[건]', '부상[명].1' : '2020_부상[명]'}, inplace=True)
df.rename(columns={'사고[건].2': '2021_사고[건]', '사망[명].2' : '2021_사망[건]', '부상[명].2' : '2021_부상[명]'}, inplace=True)
df.rename(columns={'사고[건].3': '2022_사고[건]', '사망[명].3' : '2022_사망[건]', '부상[명].3' : '2022_부상[명]'}, inplace=True)
df.rename(columns={'사고[건].4': '2023_사고[건]', '사망[명].4' : '2023_사망[건]', '부상[명].4' : '2023_부상[명]'}, inplace=True)
df.rename(columns={'연령' : ''}, inplace=True)

df

df = df.dropna(axis=0) # 결측치 행 제거

for i in range(1, len(df.index)):
  age = df.loc[i, '']
  injury_2019 = df.loc[i, '2019_부상[명]']
  injury_2020 = df.loc[i, '2020_부상[명]']
  injury_2021 = df.loc[i, '2021_부상[명]']
  injury_2022 = df.loc[i, '2022_부상[명]']
  injury_2023 = df.loc[i, '2023_부상[명]']

  injury_percent1920 = ((injury_2020 - injury_2019) / injury_2019) * 100  # 2019~2020 부상[명] 증가 퍼센트 수치
  injury_percent2021 = ((injury_2021 - injury_2020) / injury_2020) * 100  # 2020~2021 부상[명] 증가 퍼센트 수치
  injury_percent2122 = ((injury_2022 - injury_2021) / injury_2021) * 100  # 2021~2022 부상[명] 증가 퍼센트 수치
  injury_percent2223 = ((injury_2023 - injury_2022) / injury_2022) * 100  # 2022~2023 부상[명] 증가 퍼센트 수치

  accident_percent1920 = ((df.loc[i, '2020_사고[건]'] - df.loc[i, '2019_사고[건]']) / df.loc[i, '2019_사고[건]']) * 100  # 2019~2020 사고[건] 증가 퍼센트 수치
  accident_percent2021 = ((df.loc[i, '2021_사고[건]'] - df.loc[i, '2020_사고[건]']) / df.loc[i, '2020_사고[건]']) * 100  # 2020~2021 사고[건] 증가 퍼센트 수치
  accident_percent2122 = ((df.loc[i, '2022_사고[건]'] - df.loc[i, '2021_사고[건]']) / df.loc[i, '2021_사고[건]']) * 100  # 2021~2022 사고[건] 증가 퍼센트 수치
  accident_percent2223 = ((df.loc[i, '2023_사고[건]'] - df.loc[i, '2022_사고[건]']) / df.loc[i, '2022_사고[건]']) * 100  # 2022~2023 사고[건] 증가 퍼센트 수치

  death_percent1920 = ((df.loc[i, '2020_사망[건]'] - df.loc[i, '2019_사망[건]']) / df.loc[i, '2019_사망[건]']) * 100  # 2019~2020 사망[건] 증가 퍼센트 수치
  death_percent2021 = ((df.loc[i, '2021_사망[건]'] - df.loc[i, '2020_사망[건]']) / df.loc[i, '2020_사망[건]']) * 100  # 2020~2021 사망[건] 증가 퍼센트 수치
  death_percent2122 = ((df.loc[i, '2022_사망[건]'] - df.loc[i, '2021_사망[건]']) / df.loc[i, '2021_사망[건]']) * 100  # 2021~2022 사망[건] 증가 퍼센트 수치
  death_percent2223 = ((df.loc[i, '2023_사망[건]'] - df.loc[i, '2022_사망[건]']) / df.loc[i, '2022_사망[건]']) * 100  # 2022~2023 사망[건] 증가 퍼센트 수치

  print(f"{age} 부상자 증가 퍼센트 2019~2020: {injury_percent1920:.2f}%")
  print(f"{age} 부상자 증가 퍼센트 2020~2021: {injury_percent2021:.2f}%")
  print(f"{age} 부상자 증가 퍼센트 2021~2022: {injury_percent2122:.2f}%")
  print(f"{age} 부상자 증가 퍼센트 2022~2023: {injury_percent2223:.2f}%")

  print(f"{age} 사고 증가 퍼센트 2019~2020: {accident_percent1920:.2f}%")
  print(f"{age} 사고 증가 퍼센트 2020~2021: {accident_percent2021:.2f}%")
  print(f"{age} 사고 증가 퍼센트 2021~2022: {accident_percent2122:.2f}%")
  print(f"{age} 사고 증가 퍼센트 2022~2023: {accident_percent2223:.2f}%")

  print(f"{age} 사망 증가 퍼센트 2019~2020: {death_percent1920:.2f}%")
  print(f"{age} 사망 증가 퍼센트 2020~2021: {death_percent2021:.2f}%")
  print(f"{age} 사망 증가 퍼센트 2021~2022: {death_percent2122:.2f}%")
  print(f"{age} 사망 증가 퍼센트 2022~2023: {death_percent2223:.2f}%")


#%%

age = [
    '65~69세',
    '70~74세',
    '75~79세',
    '80~84세',
    '85세 이상',
]

injury_2019 = [
    df.loc[1, '2019_부상[명]'],
    df.loc[2, '2019_부상[명]'],
    df.loc[3, '2019_부상[명]'],
    df.loc[4, '2019_부상[명]'],
    df.loc[5, '2019_부상[명]'],
]

injury_2020 = [
    df.loc[1, '2020_부상[명]'],
    df.loc[2, '2020_부상[명]'],
    df.loc[3, '2020_부상[명]'],
    df.loc[4, '2020_부상[명]'],
    df.loc[5, '2020_부상[명]'],
]

injury_2021 = [
    df.loc[1, '2021_부상[명]'],
    df.loc[2, '2021_부상[명]'],
    df.loc[3, '2021_부상[명]'],
    df.loc[4, '2021_부상[명]'],
    df.loc[5, '2021_부상[명]'],
]

injury_2022 = [
    df.loc[1, '2022_부상[명]'],
    df.loc[2, '2022_부상[명]'],
    df.loc[3, '2022_부상[명]'],
    df.loc[4, '2022_부상[명]'],
    df.loc[5, '2022_부상[명]'],
]

injury_2023 = [
    df.loc[1, '2023_부상[명]'],
    df.loc[2, '2023_부상[명]'],
    df.loc[3, '2023_부상[명]'],
    df.loc[4, '2023_부상[명]'],
    df.loc[5, '2023_부상[명]'],
]

# 그래프 크기 설정
plt.figure(figsize=(10, 6))

# x축 위치 설정
x = np.arange(len(age))
width = 0.1

# 막대 그래프 그리기
plt.bar(x - 2 * width, injury_2019, width, label='2019년', color='red')
plt.bar(x - 1 * width, injury_2020, width, label='2020년', color='green')
plt.bar(x + 0 * width, injury_2021, width, label='2021년', color='blue')
plt.bar(x + 1 * width, injury_2022, width, label='2022년', color='yellow')
plt.bar(x + 2 * width, injury_2023, width, label='2023년', color='black')

# x축 레이블 설정
plt.xticks(x, age)

# 그래프 제목 설정
plt.title('연도별 노인운전자 연령층별 부상자 추이')

# 범례 표시
plt.legend()

# 그래프 표시
plt.show()

#%%

age = [
    '65~69세',
    '70~74세',
    '75~79세',
    '80~84세',
    '85세 이상',
]

accident_2019 = [
    df.loc[1, '2019_사고[건]'],
    df.loc[2, '2019_사고[건]'],
    df.loc[3, '2019_사고[건]'],
    df.loc[4, '2019_사고[건]'],
    df.loc[5, '2019_사고[건]'],
]

accident_2020 = [
    df.loc[1, '2020_사고[건]'],
    df.loc[2, '2020_사고[건]'],
    df.loc[3, '2020_사고[건]'],
    df.loc[4, '2020_사고[건]'],
    df.loc[5, '2020_사고[건]'],
]

accident_2021 = [
    df.loc[1, '2021_사고[건]'],
    df.loc[2, '2021_사고[건]'],
    df.loc[3, '2021_사고[건]'],
    df.loc[4, '2021_사고[건]'],
    df.loc[5, '2021_사고[건]'],
]

accident_2022 = [
    df.loc[1, '2022_사고[건]'],
    df.loc[2, '2022_사고[건]'],
    df.loc[3, '2022_사고[건]'],
    df.loc[4, '2022_사고[건]'],
    df.loc[5, '2022_사고[건]'],
]

accident_2023 = [
    df.loc[1, '2023_사고[건]'],
    df.loc[2, '2023_사고[건]'],
    df.loc[3, '2023_사고[건]'],
    df.loc[4, '2023_사고[건]'],
    df.loc[5, '2023_사고[건]'],
]

# 그래프 크기 설정
plt.figure(figsize=(10, 6))

# x축 위치 설정
x = np.arange(len(age))
width = 0.1

# 막대 그래프 그리기
plt.bar(x - 2 * width, accident_2019, width, label='2019년', color='red')
plt.bar(x - 1 * width, accident_2020, width, label='2020년', color='green')
plt.bar(x + 0 * width, accident_2021, width, label='2021년', color='blue')
plt.bar(x + 1 * width, accident_2022, width, label='2022년', color='yellow')
plt.bar(x + 2 * width, accident_2023, width, label='2023년', color='black')

# x축 레이블 설정
plt.xticks(x, age)

# 그래프 제목 설정
plt.title('연도별 노인운전자 연령층별 사고 추이')

# 범례 표시
plt.legend()

# 그래프 표시
plt.show()

#%%

age = [
    '65~69세',
    '70~74세',
    '75~79세',
    '80~84세',
    '85세 이상',
]

death_2019 = [
    df.loc[1, '2019_사망[건]'],
    df.loc[2, '2019_사망[건]'],
    df.loc[3, '2019_사망[건]'],
    df.loc[4, '2019_사망[건]'],
    df.loc[5, '2019_사망[건]'],
]

death_2020 = [
    df.loc[1, '2020_사망[건]'],
    df.loc[2, '2020_사망[건]'],
    df.loc[3, '2020_사망[건]'],
    df.loc[4, '2020_사망[건]'],
    df.loc[5, '2020_사망[건]'],
]

death_2021 = [
    df.loc[1, '2021_사망[건]'],
    df.loc[2, '2021_사망[건]'],
    df.loc[3, '2021_사망[건]'],
    df.loc[4, '2021_사망[건]'],
    df.loc[5, '2021_사망[건]'],
]

death_2022 = [
    df.loc[1, '2022_사망[건]'],
    df.loc[2, '2022_사망[건]'],
    df.loc[3, '2022_사망[건]'],
    df.loc[4, '2022_사망[건]'],
    df.loc[5, '2022_사망[건]'],
]

death_2023 = [
    df.loc[1, '2023_사망[건]'],
    df.loc[2, '2023_사망[건]'],
    df.loc[3, '2023_사망[건]'],
    df.loc[4, '2023_사망[건]'],
    df.loc[5, '2023_사망[건]'],
]

# 그래프 크기 설정
plt.figure(figsize=(10, 6))

# x축 위치 설정
x = np.arange(len(age))
width = 0.1

# 막대 그래프 그리기
plt.bar(x - 2 * width, death_2019, width, label='2019년', color='red')
plt.bar(x - 1 * width, death_2020, width, label='2020년', color='green')
plt.bar(x + 0 * width, death_2021, width, label='2021년', color='blue')
plt.bar(x + 1 * width, death_2022, width, label='2022년', color='yellow')
plt.bar(x + 2 * width, death_2023, width, label='2023년', color='black')

# x축 레이블 설정
plt.xticks(x, age)

# 그래프 제목 설정
plt.title('연도별 노인운전자 연령층별 사망 추이')

# 범례 표시
plt.legend()

# 그래프 표시
plt.show()
